In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv(r"C:\Users\91727\OneDrive\Desktop\Data Science Project\Data\version1\Telco_Customer_Churn.csv")

In [8]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [9]:
df.drop(columns=['customerID'], axis=1,inplace=True)

In [10]:
df.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0              Yes           Electronic check           29.85        29.85   
1               No               Mailed check           56.95       1889.5   
2              Yes               Mailed check           53.85       108.15   
3               No  Bank transfer (automatic)           42.30      1840.75   
4              Yes           Electronic check           70.70       151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

In [11]:
df = df[['gender', 'tenure','Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']]

In [12]:
df.dropna(inplace=True)

In [13]:
df.head()

gender  tenure        Contract PaperlessBilling              PaymentMethod  \
0  Female       1  Month-to-month              Yes           Electronic check   
1    Male      34        One year               No               Mailed check   
2    Male       2  Month-to-month              Yes               Mailed check   
3    Male      45        One year               No  Bank transfer (automatic)   
4  Female       2  Month-to-month              Yes           Electronic check   

   MonthlyCharges TotalCharges Churn  
0           29.85        29.85    No  
1           56.95       1889.5    No  
2           53.85       108.15   Yes  
3           42.30      1840.75    No  
4           70.70       151.65   Yes

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
gender_le = LabelEncoder()
contract_le = LabelEncoder()
paymentmethod_le = LabelEncoder()

In [16]:
gender_le.fit(df['gender'])
contract_le.fit(df['Contract'])
paymentmethod_le.fit(df['PaymentMethod'])

LabelEncoder()

In [17]:
df[["PaperlessBilling","Churn"]].replace({"Yes":1,"No":0},inplace=True)

C:\Users\91727\AppData\Local\Temp\ipykernel_21416\470112023.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[["PaperlessBilling","Churn"]].replace({"Yes":1,"No":0},inplace=True)
C:\Users\91727\AppData\Local\Temp\ipykernel_21416\470112023.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["PaperlessBilling","Churn"]].replace({"Yes":1,"No":0},inplace=True)


In [18]:
df[["PaperlessBilling","Churn"]] = df[["PaperlessBilling","Churn"]].replace({"Yes":1, "No":0})

C:\Users\91727\AppData\Local\Temp\ipykernel_21416\3817393698.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[["PaperlessBilling","Churn"]] = df[["PaperlessBilling","Churn"]].replace({"Yes":1, "No":0})


In [19]:
df.head()

gender  tenure        Contract  PaperlessBilling  \
0  Female       1  Month-to-month                 1   
1    Male      34        One year                 0   
2    Male       2  Month-to-month                 1   
3    Male      45        One year                 0   
4  Female       2  Month-to-month                 1   

               PaymentMethod  MonthlyCharges TotalCharges  Churn  
0           Electronic check           29.85        29.85      0  
1               Mailed check           56.95       1889.5      0  
2               Mailed check           53.85       108.15      1  
3  Bank transfer (automatic)           42.30      1840.75      0  
4           Electronic check           70.70       151.65      1

In [22]:
df['gender_numerical'] = gender_le.transform(df['gender'])
df['Contract_numerical'] = contract_le.transform(df['Contract'])
df['PaymentMethod_numerical'] = paymentmethod_le.transform(df['PaymentMethod'])

In [23]:
df.head()

gender  tenure        Contract  PaperlessBilling  \
0  Female       1  Month-to-month                 1   
1    Male      34        One year                 0   
2    Male       2  Month-to-month                 1   
3    Male      45        One year                 0   
4  Female       2  Month-to-month                 1   

               PaymentMethod  MonthlyCharges TotalCharges  Churn  \
0           Electronic check           29.85        29.85      0   
1               Mailed check           56.95       1889.5      0   
2               Mailed check           53.85       108.15      1   
3  Bank transfer (automatic)           42.30      1840.75      0   
4           Electronic check           70.70       151.65      1   

   gender_numerical  Contract_numerical  PaymentMethod_numerical  
0                 0                   0                        2  
1                 1                   1                        3  
2                 1                   0                        3  
3                 1                   1                        0  
4                 0                   0                        2

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   gender                   7043 non-null   object 
 1   tenure                   7043 non-null   int64  
 2   Contract                 7043 non-null   object 
 3   PaperlessBilling         7043 non-null   int64  
 4   PaymentMethod            7043 non-null   object 
 5   MonthlyCharges           7043 non-null   float64
 6   TotalCharges             7043 non-null   object 
 7   Churn                    7043 non-null   int64  
 8   gender_numerical         7043 non-null   int64  
 9   Contract_numerical       7043 non-null   int64  
 10  PaymentMethod_numerical  7043 non-null   int64  
dtypes: float64(1), int64(6), object(4)
memory usage: 605.4+ KB


In [25]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors='coerce')

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   gender                   7043 non-null   object 
 1   tenure                   7043 non-null   int64  
 2   Contract                 7043 non-null   object 
 3   PaperlessBilling         7043 non-null   int64  
 4   PaymentMethod            7043 non-null   object 
 5   MonthlyCharges           7043 non-null   float64
 6   TotalCharges             7032 non-null   float64
 7   Churn                    7043 non-null   int64  
 8   gender_numerical         7043 non-null   int64  
 9   Contract_numerical       7043 non-null   int64  
 10  PaymentMethod_numerical  7043 non-null   int64  
dtypes: float64(2), int64(6), object(3)
memory usage: 605.4+ KB


In [27]:
df.dropna(inplace=True)

In [28]:
X = df[['tenure','PaperlessBilling','MonthlyCharges','TotalCharges','gender_numerical','Contract_numerical','PaymentMethod_numerical']]

In [29]:
y = df['Churn']

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
lr_model = LogisticRegression()

In [34]:
lr_model.fit(X_train, y_train)

C:\Users\91727\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [35]:
from sklearn.tree import DecisionTreeClassifier

In [36]:
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [37]:
from sklearn.ensemble import RandomForestClassifier

In [38]:
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

RandomForestClassifier()

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [40]:
def check_accuracy(model,X_test,y_test):
    y_pred = model.predict(X_test)
    if type(model).__name__ == 'LogisticRegression':
        print("Logistic Regression Model Performance:")
    elif type(model).__name__ == 'DecisionTreeClassifier':
        print("Decision Tree Classifier Model Performance:")
    else:
        print("Random Forest Classifier Model Performance:")
    print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
    print("\nAccuracy Score:",accuracy_score(y_test,y_pred))
    print("\nClassification Report:\n",classification_report(y_test,y_pred))


In [41]:
check_accuracy(lr_model,X_test,y_test)

Logistic Regression Model Performance:
Confusion Matrix:
 [[917 116]
 [181 193]]

Accuracy Score: 0.7889125799573561

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.89      0.86      1033
           1       0.62      0.52      0.57       374

    accuracy                           0.79      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407



In [42]:
check_accuracy(dt_model,X_test,y_test)

Decision Tree Classifier Model Performance:
Confusion Matrix:
 [[834 199]
 [180 194]]

Accuracy Score: 0.7306325515280739

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.81      0.81      1033
           1       0.49      0.52      0.51       374

    accuracy                           0.73      1407
   macro avg       0.66      0.66      0.66      1407
weighted avg       0.74      0.73      0.73      1407



In [43]:
check_accuracy(rf_model,X_test,y_test)

Random Forest Classifier Model Performance:
Confusion Matrix:
 [[910 123]
 [200 174]]

Accuracy Score: 0.7704335465529495

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.88      0.85      1033
           1       0.59      0.47      0.52       374

    accuracy                           0.77      1407
   macro avg       0.70      0.67      0.68      1407
weighted avg       0.76      0.77      0.76      1407



In [44]:
import pickle

In [46]:
with open(r'C:\Users\91727\OneDrive\Desktop\Data Science Project\Model\version1\gender_le.pkl', 'wb') as f:
    pickle.dump(gender_le, f)

with open(r'C:\Users\91727\OneDrive\Desktop\Data Science Project\Model\version1\contract_le.pkl', 'wb') as f:
    pickle.dump(contract_le, f)

with open(r'C:\Users\91727\OneDrive\Desktop\Data Science Project\Model\version1\paymentmethod_le.pkl', 'wb') as f:
    pickle.dump(paymentmethod_le, f)

In [47]:
with open(r'C:\Users\91727\OneDrive\Desktop\Data Science Project\Model\version1\rf_model.pkl', 'wb') as f:
    pickle.dump(rf_model, f)